[package]
name = "shark_presence"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sys-info = "*"
sysinfo = "*"
discord-rich-presence = "*"
chrono = "*"

[target.'cfg(windows)'.dependencies]
wmi = "*"