# application id from discord developers portal
app_id: 602317448263499806

# CustomStatic - Static full custom presence
# CustomDynamic - Presence which changes every 4 secs
# SystemInfo - Presence with system info and assets from static preset
type: "SystemInfo"

# name of preset for CustomStatic presence type
static_preset_name: "some_preset"

# names of presets for CustomDynamic presence type
dynamic_preset_names:
  - "other_preset"
  - "some_preset"

with_elapsed_time: true # true or false